{% set name = "ibm-cloud-sdk-core" %}
{% set version = "3.13.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: de2baa9ac251b4ca3f616549e18e4cc6bc6220973ca02c72ff08d29247711a0a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest
    - python >=3.6
  run:
    - pyjwt <3.0.0,>=2.0.1
    - python >=3.6
    - python-dateutil <3.0.0,>=2.5.3
    - requests <3.0,>=2.20

test:
  imports:
    - ibm_cloud_sdk_core
    - ibm_cloud_sdk_core.authenticators
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/IBM/python-sdk-core
  summary: Core library used by SDKs for IBM Cloud Services
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - synapticarbors
    - BastianZim
